# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

s = input()
a_begin = 0
a_end = 0
begin = 1
end = 1
ans = 0

for i in range(0, len(s) // 2):
    if s[i] == s[len(s) - 1 - i]:
        ans += 1
    if s[i] == 'a' and begin == 1 and (i == 0 or s[i - 1] == 'a'):
        a_begin += 1
    else:
        begin = 0

if ans == len(s) // 2:
    print('Yes')
else:
    for i in range(len(s) - 1, -1, -1):
        if s[i] == 'a' and end == 1 and (i == len(s) - 1 or s[i + 1] == 'a'):
            a_end += 1
        else:
            end = 0
    ans = 0
    s_mod = 'a' * (a_end - a_begin) + s
    for i in range(0, len(s_mod) // 2):
        if s_mod[i] == s_mod[len(s_mod) - 1 - i]:
            ans += 1
    print('Yes') if ans == len(s_mod) // 2 else print('No')
