# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

n1 = int(input())
n2 = int(input())

print(((n1 // n2 * (n1 // n2 * n2 + n1 % n2)) + n2 // n1 * (n2 // n1 * n1 + n2 % n1)) // ((n1 // n2) + (n2 // n1)))