# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

n = int(input())
numbers = [int(x) for x in input().split(" ")]
if numbers[0] > 0:
    numbers[0] *= -1
for i in range(1, len(numbers) - 1):
    if numbers[i] > 0 and numbers[i] * (-1) >= numbers[i - 1] and numbers[i] * (-1) <= numbers[i + 1]:
        numbers[i] *= -1
        continue
    if numbers[i] > 0 and numbers[i] * (-1) >= numbers[i - 1] and numbers[i] * (-1) <= numbers[i + 1] * (-1):
        numbers[i] *= -1
        numbers[i + 1] *= -1
        continue
    if numbers[i] >= numbers[i - 1] and numbers[i] <= numbers[i + 1]:
        continue
    if numbers[i] < 0 and numbers[i] * (-1) >= numbers[i - 1] and numbers[i] * (-1) <= numbers[i + 1]:
        numbers[i] *= -1
        continue
    if numbers[i] < 0 and numbers[i] * (-1) >= numbers[i - 1] and numbers[i] * (-1) <= numbers[i + 1] * (-1):
        numbers[i] *= -1
        numbers[i + 1] *= -1
        continue
    if numbers[i] >= numbers[i - 1] and numbers[i] <= numbers[i + 1] * (-1):
        numbers[i + 1] *= -1
        continue
    print('No')
    break
else:
    print('Yes')
    print(*numbers)
