# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

n = int(input())
numbers = [int(x) for x in input().split(" ")]
j = 0
ans = []

for i in range(0, len(numbers)):
    if i == len(numbers) - 1:
        if numbers[i] == numbers[i - 1] + 1:
            j += 1
            ans.append(j)
        else:
            ans.append(j)
            ans.append(1)
        continue
    if j == 0:
        j += 1
        continue
    if numbers[i] == numbers[i - 1] + 1:
        j += 1
        continue
    ans.append(j)
    j = 1
print(len(ans))
print(*ans)