# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

n = int(input())
f = []
f.append(1)
f.append(1)
for i in range(2, n):
    f.append(f[i - 1] + f[i - 2])
print(f[n - 1])