# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

n = int(input())
ans = 0
for i in range(2, n + 1):
    s = str(i)
    for j in range(0, len(s)):
        if int(s[j]) % 2 != 0:
            break
    else:
        ans += 1
print(ans)