# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

s1 = input()
s2 = input()
j = -1
right = 0
left = 0
i = 0
while i < len(s2) + 1:
    if j == len(s1):
        print('NO')
        break
    if i == len(s2) and (right == i or left == i):
        i += 1
        continue
    if i == 0 or right != i and left != i:
        i = 0
        j += 1
        right = 1
        left = 1
        while j < len(s1) and s2[i] != s1[j]:
            j += 1
        i += 1
        continue
    if s2[i] == s1[(j + right) % len(s1)]:
        right += 1
    if j - left >= 0 and s2[i] == s1[j - left] or j - left < 0 and s2[i] == s1[len(s1) + j - left]:
        left += 1
    i += 1
else:
    print('YES')