# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

s = input()
print('YES') if (s[0] >= '0' and s[0] <= '9') and (s[1] > '9' and s[1] > '9') or (s[1] >= '0' and s[1] <= '9') and (s[0] > '9' and s[0] > '9') else print('NO')