# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

s = input()
ans = []
number = []
i = 0
while i < len(s):
    if s[i] > '9':
        ans.append(s[i])
        i += 1
        continue
    if s[i + 1] <= '9':
        number.append(s[i])
        i += 1
        continue
    number.append(s[i])
    for j in range(0, int(''.join(number))):
        ans.append(s[i + 1])
    number.clear()
    i += 2
print(''.join(ans))