# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

from math import sqrt

n = int(input())
for i in range(2, int(sqrt(n)) + 1):
    if n % i == 0:
        print('composite')
        break
else:
    print('prime')