# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CJu3Wy0t3wwvmZ_UMdTECZGXJQEloDd
"""

n = int(input())
numbers = [int(x) for x in input().split(" ")]

if len(numbers) == 1:
    print(numbers[0])
else:
    for i in range(1, len(numbers)):
        if i == 1:
            b = numbers[0]
        a = numbers[i]
        if b > a:
            k = a
            a = b
            b = k
        while a % b != 0:
            k = a % b
            a = b
            b = k
    print(b)